### ISSUE TITLE
Trafficraft crashes my client when playing on the server if my mouse tooltip reaches any player effect

### ISSUE THREAD

**Issue by ionutsoran** [MisterJulsen/TrafficCraft#13] opened 2024-11-08 09:11 UTC
**Version:**
 - Minecraft Version: 1.20.1
 - Forge Version : 47.3.0
 - Mod Version: trafficcraft-forge-1.20.1-rc1-1.1.0

**Describe the bug**
Whenever my mouse tooltip reaches the effect icon on the player menu my client crashes. So if the player has no effect then there is no crash. Only replicates on multiplayer worlds. Server doesn't crash only client. Same crash for creative/survival menu.

**To Reproduce**
1. Login on the server
2. Give yourself any effect or use a potion
3. Open player menu with 'E' move mouse near or on the effect status
4. Crash

**Additional context**
https://pastebin.com/N5KnCuju

**Comment by ionutsoran** [comment] 2024-11-08 09:12
I am using 1.0.4-1.20.1 of trafficraft now on my server and it works fine

**Comment by MisterJulsen** [comment] 2024-11-08 11:13
Thank you for the report. This error has been reported to me several times and it is an incompatibility with other mods that modify the tooltips or render their own tooltips. A solution to the problem is already being worked on.

**Comment by MisterJulsen** [comment] 2024-11-09 19:20
Should be fixed in the latest version

**Closed as completed by MisterJulsen** 2024-11-09 19:20 UTC
Labels: crash
